# This file was generated by GoReleaser. DO NOT EDIT.
cask "ecsdeployer@v0" do
  name "ecsdeployer@v0"
  desc "Easily deploy containerized applications to AWS ECS Fargate"
  homepage "https://ecsdeployer.com"
  version "0.5.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ecsdeployer"
  manpage "manpages/ecsdeployer.1.gz"
  bash_completion "completions/ecsdeployer.bash"
  zsh_completion "completions/ecsdeployer.zsh"
  fish_completion "completions/ecsdeployer.fish"

  on_macos do
    on_intel do
      url "https://github.com/ecsdeployer/ecsdeployer/releases/download/v#{version}/ecsdeployer_darwin_x86_64.tar.gz"
      sha256 "00106c67338df62846c3ba1ee57dd9660a19fe7a9c536ada8c5c3ab7678b15f0"
    end
    on_arm do
      url "https://github.com/ecsdeployer/ecsdeployer/releases/download/v#{version}/ecsdeployer_darwin_arm64.tar.gz"
      sha256 "c98531c7887344ec5b0d85254e077b88aa32fa6eb7a158e0140e3ba3c38e58a1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ecsdeployer/ecsdeployer/releases/download/v#{version}/ecsdeployer_linux_x86_64.tar.gz"
      sha256 "68020439e3555ecf8d8fcbf5aa05750d6250e60bdc9de9f81e58b9c1af63cc4a"
    end
    on_arm do
      url "https://github.com/ecsdeployer/ecsdeployer/releases/download/v#{version}/ecsdeployer_linux_arm64.tar.gz"
      sha256 "dc6293e2b76e08a00f57887953f5460306728b2968deecd46c4eadbc58a56cdb"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ecsdeployer"]
  end

  # No zap stanza required
end
