# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ecsdeployer < Formula
  desc "Easily deploy containerized applications to AWS ECS Fargate"
  homepage "https://ecsdeployer.com"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ecsdeployer/ecsdeployer/releases/download/v0.2.0/ecsdeployer_darwin_x86_64.tar.gz"
      sha256 "57b27977e524df617a9999071833a117798655e962313be993726add378a7d43"

      def install
        bin.install "ecsdeployer"
        bash_completion.install "completions/ecsdeployer.bash" => "ecsdeployer"
        fish_completion.install "completions/ecsdeployer.fish" => "ecsdeployer.fish"
        zsh_completion.install "completions/ecsdeployer.zsh" => "_ecsdeployer"
        man1.install "manpages/ecsdeployer.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ecsdeployer/ecsdeployer/releases/download/v0.2.0/ecsdeployer_darwin_arm64.tar.gz"
      sha256 "485152868f1123f87bf69c00f2024ffc3e5830b7e017a4ec28a64023b2947847"

      def install
        bin.install "ecsdeployer"
        bash_completion.install "completions/ecsdeployer.bash" => "ecsdeployer"
        fish_completion.install "completions/ecsdeployer.fish" => "ecsdeployer.fish"
        zsh_completion.install "completions/ecsdeployer.zsh" => "_ecsdeployer"
        man1.install "manpages/ecsdeployer.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ecsdeployer/ecsdeployer/releases/download/v0.2.0/ecsdeployer_linux_x86_64.tar.gz"
      sha256 "538e83c0faa15f4fa1bb2a0ff389d615d7f357238734b25a616bd9a95f555af2"

      def install
        bin.install "ecsdeployer"
        bash_completion.install "completions/ecsdeployer.bash" => "ecsdeployer"
        fish_completion.install "completions/ecsdeployer.fish" => "ecsdeployer.fish"
        zsh_completion.install "completions/ecsdeployer.zsh" => "_ecsdeployer"
        man1.install "manpages/ecsdeployer.1.gz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ecsdeployer/ecsdeployer/releases/download/v0.2.0/ecsdeployer_linux_arm64.tar.gz"
      sha256 "26d0666181decfaf497d6dbdd0555c5bed5219d107236dd2cf56268212ad3091"

      def install
        bin.install "ecsdeployer"
        bash_completion.install "completions/ecsdeployer.bash" => "ecsdeployer"
        fish_completion.install "completions/ecsdeployer.fish" => "ecsdeployer.fish"
        zsh_completion.install "completions/ecsdeployer.zsh" => "_ecsdeployer"
        man1.install "manpages/ecsdeployer.1.gz"
      end
    end
  end

  test do
    system "#{bin} --version"
  end
end
