# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EcsdeployerATv0 < Formula
  desc "Easily deploy containerized applications to AWS ECS Fargate"
  homepage "https://ecsdeployer.com"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ecsdeployer/ecsdeployer/releases/download/v0.3.0/ecsdeployer_darwin_x86_64.tar.gz"
      sha256 "7407edf4b8a9abc30e824e5139eac14a38dd6993369a6852a0bb400120aa4ca1"

      def install
        bin.install "ecsdeployer"
        bash_completion.install "completions/ecsdeployer.bash" => "ecsdeployer"
        fish_completion.install "completions/ecsdeployer.fish" => "ecsdeployer.fish"
        zsh_completion.install "completions/ecsdeployer.zsh" => "_ecsdeployer"
        man1.install "manpages/ecsdeployer.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ecsdeployer/ecsdeployer/releases/download/v0.3.0/ecsdeployer_darwin_arm64.tar.gz"
      sha256 "31553b46ec0d2db177fe5385c06b99d6f37ab3a12c69fa4a3454adb5a7a4c458"

      def install
        bin.install "ecsdeployer"
        bash_completion.install "completions/ecsdeployer.bash" => "ecsdeployer"
        fish_completion.install "completions/ecsdeployer.fish" => "ecsdeployer.fish"
        zsh_completion.install "completions/ecsdeployer.zsh" => "_ecsdeployer"
        man1.install "manpages/ecsdeployer.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ecsdeployer/ecsdeployer/releases/download/v0.3.0/ecsdeployer_linux_arm64.tar.gz"
      sha256 "c50bfcc332cdbc1c2c58283db59976ad62f8762ebbf573f16d20f7098f442f91"

      def install
        bin.install "ecsdeployer"
        bash_completion.install "completions/ecsdeployer.bash" => "ecsdeployer"
        fish_completion.install "completions/ecsdeployer.fish" => "ecsdeployer.fish"
        zsh_completion.install "completions/ecsdeployer.zsh" => "_ecsdeployer"
        man1.install "manpages/ecsdeployer.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ecsdeployer/ecsdeployer/releases/download/v0.3.0/ecsdeployer_linux_x86_64.tar.gz"
      sha256 "de85ba572c4348a1f0556a2ef1b9c48149a8f025dbc3b0e8bc22b17bfcbf62b2"

      def install
        bin.install "ecsdeployer"
        bash_completion.install "completions/ecsdeployer.bash" => "ecsdeployer"
        fish_completion.install "completions/ecsdeployer.fish" => "ecsdeployer.fish"
        zsh_completion.install "completions/ecsdeployer.zsh" => "_ecsdeployer"
        man1.install "manpages/ecsdeployer.1.gz"
      end
    end
  end

  test do
    system "#{bin} --version"
  end
end
