# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ecsdeployer < Formula
  desc "Easily deploy containerized applications to AWS ECS Fargate"
  homepage "https://ecsdeployer.com"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ecsdeployer/ecsdeployer/releases/download/v0.4.0/ecsdeployer_darwin_x86_64.tar.gz"
      sha256 "1c54ff788f30c4c3fd1df1289e848f5f64eb84845cf114645718fb2afcb54bd7"

      def install
        bin.install "ecsdeployer"
        bash_completion.install "completions/ecsdeployer.bash" => "ecsdeployer"
        fish_completion.install "completions/ecsdeployer.fish" => "ecsdeployer.fish"
        zsh_completion.install "completions/ecsdeployer.zsh" => "_ecsdeployer"
        man1.install "manpages/ecsdeployer.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ecsdeployer/ecsdeployer/releases/download/v0.4.0/ecsdeployer_darwin_arm64.tar.gz"
      sha256 "47cf2835b8eb6da85131554d8b11bf6f6ead92b0c152cc926a162fb917cb2fe8"

      def install
        bin.install "ecsdeployer"
        bash_completion.install "completions/ecsdeployer.bash" => "ecsdeployer"
        fish_completion.install "completions/ecsdeployer.fish" => "ecsdeployer.fish"
        zsh_completion.install "completions/ecsdeployer.zsh" => "_ecsdeployer"
        man1.install "manpages/ecsdeployer.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ecsdeployer/ecsdeployer/releases/download/v0.4.0/ecsdeployer_linux_x86_64.tar.gz"
      sha256 "c762921f339df3daf8533fb703bd2502e0c496d393822df7c11dfa12e4062b32"

      def install
        bin.install "ecsdeployer"
        bash_completion.install "completions/ecsdeployer.bash" => "ecsdeployer"
        fish_completion.install "completions/ecsdeployer.fish" => "ecsdeployer.fish"
        zsh_completion.install "completions/ecsdeployer.zsh" => "_ecsdeployer"
        man1.install "manpages/ecsdeployer.1.gz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ecsdeployer/ecsdeployer/releases/download/v0.4.0/ecsdeployer_linux_arm64.tar.gz"
      sha256 "7d8c9372cde579fe7c16bb239667586495f46450e86a707fe98db2dbe983cfc9"

      def install
        bin.install "ecsdeployer"
        bash_completion.install "completions/ecsdeployer.bash" => "ecsdeployer"
        fish_completion.install "completions/ecsdeployer.fish" => "ecsdeployer.fish"
        zsh_completion.install "completions/ecsdeployer.zsh" => "_ecsdeployer"
        man1.install "manpages/ecsdeployer.1.gz"
      end
    end
  end

  test do
    system "#{bin} --version"
  end
end
