# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EcsdeployerATv0 < Formula
  desc "Easily deploy containerized applications to AWS ECS Fargate"
  homepage "https://ecsdeployer.com"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ecsdeployer/ecsdeployer/releases/download/v0.1.0/ecsdeployer_darwin_x86_64.tar.gz"
      sha256 "6e959d2587b1906c3bbb3eac844f1235aed8790ca48a10b3826bc53380b18f89"

      def install
        bin.install "ecsdeployer"
        bash_completion.install "completions/ecsdeployer.bash" => "ecsdeployer"
        fish_completion.install "completions/ecsdeployer.fish" => "ecsdeployer.fish"
        zsh_completion.install "completions/ecsdeployer.zsh" => "_ecsdeployer"
        man1.install "manpages/ecsdeployer.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ecsdeployer/ecsdeployer/releases/download/v0.1.0/ecsdeployer_darwin_arm64.tar.gz"
      sha256 "ad62703fba11d90125b7bf1bd49459484b145f262b8459628722c1d027dcbfc8"

      def install
        bin.install "ecsdeployer"
        bash_completion.install "completions/ecsdeployer.bash" => "ecsdeployer"
        fish_completion.install "completions/ecsdeployer.fish" => "ecsdeployer.fish"
        zsh_completion.install "completions/ecsdeployer.zsh" => "_ecsdeployer"
        man1.install "manpages/ecsdeployer.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ecsdeployer/ecsdeployer/releases/download/v0.1.0/ecsdeployer_linux_x86_64.tar.gz"
      sha256 "56e29bf591324cf596a089c4b0434b96b92dc92802de9643585c93906fe919de"

      def install
        bin.install "ecsdeployer"
        bash_completion.install "completions/ecsdeployer.bash" => "ecsdeployer"
        fish_completion.install "completions/ecsdeployer.fish" => "ecsdeployer.fish"
        zsh_completion.install "completions/ecsdeployer.zsh" => "_ecsdeployer"
        man1.install "manpages/ecsdeployer.1.gz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ecsdeployer/ecsdeployer/releases/download/v0.1.0/ecsdeployer_linux_arm64.tar.gz"
      sha256 "d6d21d6625e6709992020c1b7a9b0928d8b6edd203d0b277910141581672429d"

      def install
        bin.install "ecsdeployer"
        bash_completion.install "completions/ecsdeployer.bash" => "ecsdeployer"
        fish_completion.install "completions/ecsdeployer.fish" => "ecsdeployer.fish"
        zsh_completion.install "completions/ecsdeployer.zsh" => "_ecsdeployer"
        man1.install "manpages/ecsdeployer.1.gz"
      end
    end
  end

  test do
    system "#{bin} --version"
  end
end
